# Generated by Django 3.2 on 2021-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_stockcontrol_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='percent',
            field=models.IntegerField(verbose_name='降水確率'),
        ),
    ]
