# Generated by Django 3.2 on 2021-05-01 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_weather_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 9, 15, 51, 965281, tzinfo=utc), verbose_name='日付'),
        ),
    ]
