# Generated by Django 3.2 on 2021-05-01 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
