# Generated by Django 3.2 on 2021-05-03 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 2, 23, 47, 539700), verbose_name='日付'),
        ),
    ]
