# Generated by Django 3.2 on 2021-05-03 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210504_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='num_of_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='人数'),
        ),
    ]
